## Code Book for Course Project

### Overview

[Source](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip) of the original data:

	https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

[Full Description](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) at the site where the data was obtained:

	http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

### Process
The script run_analysis.R performs the following process to clean up the data and create tiny data sets:
1.	Merge the training and test sets to create one data set.
2.	Reads features.txt and uses only the measurements on the mean and standard deviation for each measurement.
3.	Reads activity_labels.txt and applies human readable activity names to name the activities in the data set.
4.	Labels the data set with descriptive names. (Names are converted to lower case; underscores and brackets are removed.)
5.	Merges the features with activity labels and subject IDs. The result is saved as Tidy_Data.txt.
### Variables
- X_test - table contents of test/X_test.txt
- X_train - table contents of train/X_train.txt
- Y_test - table contents of test/Y_test.txt
- Y_train - table contents of train/Y_train.txt
- X_merge - Measurement data. Combined data set of the two variables, X_test & X_train
- Y_merge - Measurement data. Combined data set of the two variables, Y_test & Y_train
- subject_test - table contents of test/subject_test.txt
- subject_train - table contents of test/subject_train.txt 
- Subject_merge - Combined data set of the two variables, subject_test & subject_train
- features - table contents of features.txt
- features_extracts - Names of for data columns derived from featuresList
- names – extracts from feature_extract variable
- activity_labels - table contents of activity_labels.txt
- clean_data – combined data from Subject_merge, X_merge and Y_merge
- tidy_data – order clean_data table by SubjectID and Activity.
### Output
tidyData.txt
tidyData.txt is a 10299x68 data frame.
-	The first column contains subject IDs.
-	The second column contains activity names.
-	The last 66 columns are measurements.
Subject IDs are integers between 1 and 30.